### ISSUE TITLE
Olvass el!

### ISSUE THREAD

**Issue by istvanbalog** [sidpromo/schProject2016#1]
@bence2393 @sidpromo 
Üdv! A hibabejelentésekhez, kérdésekhez, javaslatokhoz csináljatok **Issue**-kat. Ezeket majd meg tudjuk mutatni az oktatóknak, meg mindenkinek. Ne feledjétek, hogy a Repository publikus és az oktatók látni fogják, amit csinálunk!

**Tippek:**
- Használjátok bátran a formázásokat és mindig fejtsétek ki részletesen a problémát.
- @ jel után tudjuk egymást tagelni, de a hibák kiosztását jobb oldalon az "Assignees"-nél csináljátok.
- Jobb oldalon a "Labels"-nél tudjátok kiválasztani, hogy mi a kategória: bug, segítségkérés stb.
- Tudtok fájlokat csatolni az Issue-khoz, például képeket a hibáról stb.

**Comment by istvanbalog** [comment]
Aki elolvasta, az kommenteljen valamit!

**Comment by sidpromo** [comment]
Copy that

**Comment by istvanbalog** [comment]
Like! :D

**Comment by bence2393** [comment]
got it :D
