### ISSUE TITLE
Exam hozzáadásánál ellenőrizni kell az idegen kulcsokat

### ISSUE THREAD

**Issue by istvanbalog** [sidpromo/schProject2016#39]
Ha az idegen kulcs id-ja olyan id-ra mutat, ami nem létezik a másik táblában, akkor el fog szállni. Ha az adatok jók, akkor ilyennek elvileg nem kéne előfordulnia.

**Comment by sidpromo** [comment]
repóban a törlő metódusok-ban kéne arra ügyelni, ha egy tárgyat törlünk a hozzá tartozó táblákból is töröljenek a rekordok. pl.: Exam törlésekor ExamUserek is ...
